services:
  app:
    build: .
    container_name: notification-service-app
    env_file:
      - .env
    ports:
      - "9089:9089"
    depends_on:
      - kafka
    restart: always
    networks:
      - music-go-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: notification-service-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    networks:
      - music-go-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: notification-service-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - music-go-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: notification-service-kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - music-go-network

  kafka-init:
    image: confluentinc/cp-kafka:latest
    container_name: notification-service-kafka-init
    depends_on:
      - kafka
    command: >
      bash -c "echo 'Waiting for Kafka to be ready...' &&
      cub kafka-ready -b kafka:19092 1 120 &&
      echo 'Creating topic email-notifications...' &&
      kafka-topics --create --if-not-exists --topic email-notifications --bootstrap-server kafka:19092 --partitions 1 --replication-factor 1 &&
      echo 'Topic created.'"
    networks:
      - music-go-network

volumes:
  kafka_data:
    driver: local
  zookeeper_data:
    driver: local
  zookeeper_log:
    driver: local

networks:
  music-go-network:
    name: music-go-network
    external: true
