services:
  app:
    build: .
    container_name: notification-service-app
    env_file:
      - .env
    ports:
      - "9089:9089"
    depends_on:
      - kafka
    restart: always
    networks:
      - music-go-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: notification-service-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - music-go-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: notification-service-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - music-go-network

volumes:
  kafka_data:
    driver: local

networks:
  music-go-network:
    name: music-go-network
    external: true
