services:
  postgres:
    image: postgres:17-alpine
    container_name: content-service-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - music-go-network

  app:
    build: .
    container_name: content-service-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - music-go-network

volumes:
  postgres_data:
    driver: local

networks:
  music-go-network:
    name: music-go-network
    external: true
