// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package track

import (
	"context"
	"mime/multipart"

	"github.com/ocenb/music-go/content-service/internal/models"
	"github.com/ocenb/music-go/content-service/internal/services/file"
	"github.com/ocenb/music-protos/gen/searchservice"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepo creates a new instance of MockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepo {
	mock := &MockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepo is an autogenerated mock type for the Repo type
type MockRepo struct {
	mock.Mock
}

type MockRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepo) EXPECT() *MockRepo_Expecter {
	return &MockRepo_Expecter{mock: &_m.Mock}
}

// AddPlay provides a mock function for the type MockRepo
func (_mock *MockRepo) AddPlay(ctx context.Context, trackID int64) error {
	ret := _mock.Called(ctx, trackID)

	if len(ret) == 0 {
		panic("no return value specified for AddPlay")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, trackID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_AddPlay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPlay'
type MockRepo_AddPlay_Call struct {
	*mock.Call
}

// AddPlay is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID int64
func (_e *MockRepo_Expecter) AddPlay(ctx interface{}, trackID interface{}) *MockRepo_AddPlay_Call {
	return &MockRepo_AddPlay_Call{Call: _e.mock.On("AddPlay", ctx, trackID)}
}

func (_c *MockRepo_AddPlay_Call) Run(run func(ctx context.Context, trackID int64)) *MockRepo_AddPlay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_AddPlay_Call) Return(err error) *MockRepo_AddPlay_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_AddPlay_Call) RunAndReturn(run func(ctx context.Context, trackID int64) error) *MockRepo_AddPlay_Call {
	_c.Call.Return(run)
	return _c
}

// AddToLiked provides a mock function for the type MockRepo
func (_mock *MockRepo) AddToLiked(ctx context.Context, currentUserID int64, trackID int64) error {
	ret := _mock.Called(ctx, currentUserID, trackID)

	if len(ret) == 0 {
		panic("no return value specified for AddToLiked")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, currentUserID, trackID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_AddToLiked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToLiked'
type MockRepo_AddToLiked_Call struct {
	*mock.Call
}

// AddToLiked is a helper method to define mock.On call
//   - ctx context.Context
//   - currentUserID int64
//   - trackID int64
func (_e *MockRepo_Expecter) AddToLiked(ctx interface{}, currentUserID interface{}, trackID interface{}) *MockRepo_AddToLiked_Call {
	return &MockRepo_AddToLiked_Call{Call: _e.mock.On("AddToLiked", ctx, currentUserID, trackID)}
}

func (_c *MockRepo_AddToLiked_Call) Run(run func(ctx context.Context, currentUserID int64, trackID int64)) *MockRepo_AddToLiked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_AddToLiked_Call) Return(err error) *MockRepo_AddToLiked_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_AddToLiked_Call) RunAndReturn(run func(ctx context.Context, currentUserID int64, trackID int64) error) *MockRepo_AddToLiked_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeChangeableID provides a mock function for the type MockRepo
func (_mock *MockRepo) ChangeChangeableID(ctx context.Context, trackID int64, changeableID string) error {
	ret := _mock.Called(ctx, trackID, changeableID)

	if len(ret) == 0 {
		panic("no return value specified for ChangeChangeableID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, trackID, changeableID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_ChangeChangeableID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeChangeableID'
type MockRepo_ChangeChangeableID_Call struct {
	*mock.Call
}

// ChangeChangeableID is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID int64
//   - changeableID string
func (_e *MockRepo_Expecter) ChangeChangeableID(ctx interface{}, trackID interface{}, changeableID interface{}) *MockRepo_ChangeChangeableID_Call {
	return &MockRepo_ChangeChangeableID_Call{Call: _e.mock.On("ChangeChangeableID", ctx, trackID, changeableID)}
}

func (_c *MockRepo_ChangeChangeableID_Call) Run(run func(ctx context.Context, trackID int64, changeableID string)) *MockRepo_ChangeChangeableID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_ChangeChangeableID_Call) Return(err error) *MockRepo_ChangeChangeableID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_ChangeChangeableID_Call) RunAndReturn(run func(ctx context.Context, trackID int64, changeableID string) error) *MockRepo_ChangeChangeableID_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeImage provides a mock function for the type MockRepo
func (_mock *MockRepo) ChangeImage(ctx context.Context, trackID int64, image string) error {
	ret := _mock.Called(ctx, trackID, image)

	if len(ret) == 0 {
		panic("no return value specified for ChangeImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, trackID, image)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_ChangeImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeImage'
type MockRepo_ChangeImage_Call struct {
	*mock.Call
}

// ChangeImage is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID int64
//   - image string
func (_e *MockRepo_Expecter) ChangeImage(ctx interface{}, trackID interface{}, image interface{}) *MockRepo_ChangeImage_Call {
	return &MockRepo_ChangeImage_Call{Call: _e.mock.On("ChangeImage", ctx, trackID, image)}
}

func (_c *MockRepo_ChangeImage_Call) Run(run func(ctx context.Context, trackID int64, image string)) *MockRepo_ChangeImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_ChangeImage_Call) Return(err error) *MockRepo_ChangeImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_ChangeImage_Call) RunAndReturn(run func(ctx context.Context, trackID int64, image string) error) *MockRepo_ChangeImage_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeTitle provides a mock function for the type MockRepo
func (_mock *MockRepo) ChangeTitle(ctx context.Context, trackID int64, title string) error {
	ret := _mock.Called(ctx, trackID, title)

	if len(ret) == 0 {
		panic("no return value specified for ChangeTitle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, trackID, title)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_ChangeTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeTitle'
type MockRepo_ChangeTitle_Call struct {
	*mock.Call
}

// ChangeTitle is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID int64
//   - title string
func (_e *MockRepo_Expecter) ChangeTitle(ctx interface{}, trackID interface{}, title interface{}) *MockRepo_ChangeTitle_Call {
	return &MockRepo_ChangeTitle_Call{Call: _e.mock.On("ChangeTitle", ctx, trackID, title)}
}

func (_c *MockRepo_ChangeTitle_Call) Run(run func(ctx context.Context, trackID int64, title string)) *MockRepo_ChangeTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_ChangeTitle_Call) Return(err error) *MockRepo_ChangeTitle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_ChangeTitle_Call) RunAndReturn(run func(ctx context.Context, trackID int64, title string) error) *MockRepo_ChangeTitle_Call {
	_c.Call.Return(run)
	return _c
}

// CheckChangeableID provides a mock function for the type MockRepo
func (_mock *MockRepo) CheckChangeableID(ctx context.Context, userID int64, changeableID string) (bool, error) {
	ret := _mock.Called(ctx, userID, changeableID)

	if len(ret) == 0 {
		panic("no return value specified for CheckChangeableID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (bool, error)); ok {
		return returnFunc(ctx, userID, changeableID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) bool); ok {
		r0 = returnFunc(ctx, userID, changeableID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, changeableID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_CheckChangeableID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckChangeableID'
type MockRepo_CheckChangeableID_Call struct {
	*mock.Call
}

// CheckChangeableID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - changeableID string
func (_e *MockRepo_Expecter) CheckChangeableID(ctx interface{}, userID interface{}, changeableID interface{}) *MockRepo_CheckChangeableID_Call {
	return &MockRepo_CheckChangeableID_Call{Call: _e.mock.On("CheckChangeableID", ctx, userID, changeableID)}
}

func (_c *MockRepo_CheckChangeableID_Call) Run(run func(ctx context.Context, userID int64, changeableID string)) *MockRepo_CheckChangeableID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_CheckChangeableID_Call) Return(b bool, err error) *MockRepo_CheckChangeableID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepo_CheckChangeableID_Call) RunAndReturn(run func(ctx context.Context, userID int64, changeableID string) (bool, error)) *MockRepo_CheckChangeableID_Call {
	_c.Call.Return(run)
	return _c
}

// CheckPermission provides a mock function for the type MockRepo
func (_mock *MockRepo) CheckPermission(ctx context.Context, userID int64, trackID int64) (bool, error) {
	ret := _mock.Called(ctx, userID, trackID)

	if len(ret) == 0 {
		panic("no return value specified for CheckPermission")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (bool, error)); ok {
		return returnFunc(ctx, userID, trackID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) bool); ok {
		r0 = returnFunc(ctx, userID, trackID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, userID, trackID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_CheckPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPermission'
type MockRepo_CheckPermission_Call struct {
	*mock.Call
}

// CheckPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - trackID int64
func (_e *MockRepo_Expecter) CheckPermission(ctx interface{}, userID interface{}, trackID interface{}) *MockRepo_CheckPermission_Call {
	return &MockRepo_CheckPermission_Call{Call: _e.mock.On("CheckPermission", ctx, userID, trackID)}
}

func (_c *MockRepo_CheckPermission_Call) Run(run func(ctx context.Context, userID int64, trackID int64)) *MockRepo_CheckPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_CheckPermission_Call) Return(b bool, err error) *MockRepo_CheckPermission_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepo_CheckPermission_Call) RunAndReturn(run func(ctx context.Context, userID int64, trackID int64) (bool, error)) *MockRepo_CheckPermission_Call {
	_c.Call.Return(run)
	return _c
}

// CheckTitle provides a mock function for the type MockRepo
func (_mock *MockRepo) CheckTitle(ctx context.Context, userID int64, title string) (bool, error) {
	ret := _mock.Called(ctx, userID, title)

	if len(ret) == 0 {
		panic("no return value specified for CheckTitle")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (bool, error)); ok {
		return returnFunc(ctx, userID, title)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) bool); ok {
		r0 = returnFunc(ctx, userID, title)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_CheckTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckTitle'
type MockRepo_CheckTitle_Call struct {
	*mock.Call
}

// CheckTitle is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - title string
func (_e *MockRepo_Expecter) CheckTitle(ctx interface{}, userID interface{}, title interface{}) *MockRepo_CheckTitle_Call {
	return &MockRepo_CheckTitle_Call{Call: _e.mock.On("CheckTitle", ctx, userID, title)}
}

func (_c *MockRepo_CheckTitle_Call) Run(run func(ctx context.Context, userID int64, title string)) *MockRepo_CheckTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_CheckTitle_Call) Return(b bool, err error) *MockRepo_CheckTitle_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepo_CheckTitle_Call) RunAndReturn(run func(ctx context.Context, userID int64, title string) (bool, error)) *MockRepo_CheckTitle_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepo
func (_mock *MockRepo) Create(ctx context.Context, userID int64, username string, title string, changeableID string, audio string, image string, duration int64) (*models.TrackModel, error) {
	ret := _mock.Called(ctx, userID, username, title, changeableID, audio, image, duration)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.TrackModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, string, string, string, int64) (*models.TrackModel, error)); ok {
		return returnFunc(ctx, userID, username, title, changeableID, audio, image, duration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, string, string, string, int64) *models.TrackModel); ok {
		r0 = returnFunc(ctx, userID, username, title, changeableID, audio, image, duration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TrackModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string, string, string, string, int64) error); ok {
		r1 = returnFunc(ctx, userID, username, title, changeableID, audio, image, duration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - username string
//   - title string
//   - changeableID string
//   - audio string
//   - image string
//   - duration int64
func (_e *MockRepo_Expecter) Create(ctx interface{}, userID interface{}, username interface{}, title interface{}, changeableID interface{}, audio interface{}, image interface{}, duration interface{}) *MockRepo_Create_Call {
	return &MockRepo_Create_Call{Call: _e.mock.On("Create", ctx, userID, username, title, changeableID, audio, image, duration)}
}

func (_c *MockRepo_Create_Call) Run(run func(ctx context.Context, userID int64, username string, title string, changeableID string, audio string, image string, duration int64)) *MockRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 int64
		if args[7] != nil {
			arg7 = args[7].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockRepo_Create_Call) Return(trackModel *models.TrackModel, err error) *MockRepo_Create_Call {
	_c.Call.Return(trackModel, err)
	return _c
}

func (_c *MockRepo_Create_Call) RunAndReturn(run func(ctx context.Context, userID int64, username string, title string, changeableID string, audio string, image string, duration int64) (*models.TrackModel, error)) *MockRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepo
func (_mock *MockRepo) Delete(ctx context.Context, trackID int64) error {
	ret := _mock.Called(ctx, trackID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, trackID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID int64
func (_e *MockRepo_Expecter) Delete(ctx interface{}, trackID interface{}) *MockRepo_Delete_Call {
	return &MockRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, trackID)}
}

func (_c *MockRepo_Delete_Call) Run(run func(ctx context.Context, trackID int64)) *MockRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_Delete_Call) Return(err error) *MockRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, trackID int64) error) *MockRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByChangeableID provides a mock function for the type MockRepo
func (_mock *MockRepo) GetByChangeableID(ctx context.Context, username string, changeableID string, currentUserID int64) (*models.TrackWithLikedModel, error) {
	ret := _mock.Called(ctx, username, changeableID, currentUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetByChangeableID")
	}

	var r0 *models.TrackWithLikedModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) (*models.TrackWithLikedModel, error)); ok {
		return returnFunc(ctx, username, changeableID, currentUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) *models.TrackWithLikedModel); ok {
		r0 = returnFunc(ctx, username, changeableID, currentUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TrackWithLikedModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = returnFunc(ctx, username, changeableID, currentUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetByChangeableID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByChangeableID'
type MockRepo_GetByChangeableID_Call struct {
	*mock.Call
}

// GetByChangeableID is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - changeableID string
//   - currentUserID int64
func (_e *MockRepo_Expecter) GetByChangeableID(ctx interface{}, username interface{}, changeableID interface{}, currentUserID interface{}) *MockRepo_GetByChangeableID_Call {
	return &MockRepo_GetByChangeableID_Call{Call: _e.mock.On("GetByChangeableID", ctx, username, changeableID, currentUserID)}
}

func (_c *MockRepo_GetByChangeableID_Call) Run(run func(ctx context.Context, username string, changeableID string, currentUserID int64)) *MockRepo_GetByChangeableID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepo_GetByChangeableID_Call) Return(trackWithLikedModel *models.TrackWithLikedModel, err error) *MockRepo_GetByChangeableID_Call {
	_c.Call.Return(trackWithLikedModel, err)
	return _c
}

func (_c *MockRepo_GetByChangeableID_Call) RunAndReturn(run func(ctx context.Context, username string, changeableID string, currentUserID int64) (*models.TrackWithLikedModel, error)) *MockRepo_GetByChangeableID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRepo
func (_mock *MockRepo) GetByID(ctx context.Context, trackID int64, currentUserID int64) (*models.TrackWithLikedModel, error) {
	ret := _mock.Called(ctx, trackID, currentUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.TrackWithLikedModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*models.TrackWithLikedModel, error)); ok {
		return returnFunc(ctx, trackID, currentUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *models.TrackWithLikedModel); ok {
		r0 = returnFunc(ctx, trackID, currentUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TrackWithLikedModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, trackID, currentUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID int64
//   - currentUserID int64
func (_e *MockRepo_Expecter) GetByID(ctx interface{}, trackID interface{}, currentUserID interface{}) *MockRepo_GetByID_Call {
	return &MockRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, trackID, currentUserID)}
}

func (_c *MockRepo_GetByID_Call) Run(run func(ctx context.Context, trackID int64, currentUserID int64)) *MockRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_GetByID_Call) Return(trackWithLikedModel *models.TrackWithLikedModel, err error) *MockRepo_GetByID_Call {
	_c.Call.Return(trackWithLikedModel, err)
	return _c
}

func (_c *MockRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, trackID int64, currentUserID int64) (*models.TrackWithLikedModel, error)) *MockRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMany provides a mock function for the type MockRepo
func (_mock *MockRepo) GetMany(ctx context.Context, userID int64, currentUserID int64, take int, lastID int64) ([]*models.TrackWithLikedModel, error) {
	ret := _mock.Called(ctx, userID, currentUserID, take, lastID)

	if len(ret) == 0 {
		panic("no return value specified for GetMany")
	}

	var r0 []*models.TrackWithLikedModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, int, int64) ([]*models.TrackWithLikedModel, error)); ok {
		return returnFunc(ctx, userID, currentUserID, take, lastID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, int, int64) []*models.TrackWithLikedModel); ok {
		r0 = returnFunc(ctx, userID, currentUserID, take, lastID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.TrackWithLikedModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, int, int64) error); ok {
		r1 = returnFunc(ctx, userID, currentUserID, take, lastID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMany'
type MockRepo_GetMany_Call struct {
	*mock.Call
}

// GetMany is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - currentUserID int64
//   - take int
//   - lastID int64
func (_e *MockRepo_Expecter) GetMany(ctx interface{}, userID interface{}, currentUserID interface{}, take interface{}, lastID interface{}) *MockRepo_GetMany_Call {
	return &MockRepo_GetMany_Call{Call: _e.mock.On("GetMany", ctx, userID, currentUserID, take, lastID)}
}

func (_c *MockRepo_GetMany_Call) Run(run func(ctx context.Context, userID int64, currentUserID int64, take int, lastID int64)) *MockRepo_GetMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepo_GetMany_Call) Return(trackWithLikedModels []*models.TrackWithLikedModel, err error) *MockRepo_GetMany_Call {
	_c.Call.Return(trackWithLikedModels, err)
	return _c
}

func (_c *MockRepo_GetMany_Call) RunAndReturn(run func(ctx context.Context, userID int64, currentUserID int64, take int, lastID int64) ([]*models.TrackWithLikedModel, error)) *MockRepo_GetMany_Call {
	_c.Call.Return(run)
	return _c
}

// GetManyLiked provides a mock function for the type MockRepo
func (_mock *MockRepo) GetManyLiked(ctx context.Context, currentUserID int64) ([]*models.UserLikedTrackModel, error) {
	ret := _mock.Called(ctx, currentUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetManyLiked")
	}

	var r0 []*models.UserLikedTrackModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]*models.UserLikedTrackModel, error)); ok {
		return returnFunc(ctx, currentUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []*models.UserLikedTrackModel); ok {
		r0 = returnFunc(ctx, currentUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.UserLikedTrackModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, currentUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetManyLiked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManyLiked'
type MockRepo_GetManyLiked_Call struct {
	*mock.Call
}

// GetManyLiked is a helper method to define mock.On call
//   - ctx context.Context
//   - currentUserID int64
func (_e *MockRepo_Expecter) GetManyLiked(ctx interface{}, currentUserID interface{}) *MockRepo_GetManyLiked_Call {
	return &MockRepo_GetManyLiked_Call{Call: _e.mock.On("GetManyLiked", ctx, currentUserID)}
}

func (_c *MockRepo_GetManyLiked_Call) Run(run func(ctx context.Context, currentUserID int64)) *MockRepo_GetManyLiked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_GetManyLiked_Call) Return(userLikedTrackModels []*models.UserLikedTrackModel, err error) *MockRepo_GetManyLiked_Call {
	_c.Call.Return(userLikedTrackModels, err)
	return _c
}

func (_c *MockRepo_GetManyLiked_Call) RunAndReturn(run func(ctx context.Context, currentUserID int64) ([]*models.UserLikedTrackModel, error)) *MockRepo_GetManyLiked_Call {
	_c.Call.Return(run)
	return _c
}

// GetManyPopular provides a mock function for the type MockRepo
func (_mock *MockRepo) GetManyPopular(ctx context.Context, userID int64, currentUserID int64, take int, lastID int64) ([]*models.TrackWithLikedModel, error) {
	ret := _mock.Called(ctx, userID, currentUserID, take, lastID)

	if len(ret) == 0 {
		panic("no return value specified for GetManyPopular")
	}

	var r0 []*models.TrackWithLikedModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, int, int64) ([]*models.TrackWithLikedModel, error)); ok {
		return returnFunc(ctx, userID, currentUserID, take, lastID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, int, int64) []*models.TrackWithLikedModel); ok {
		r0 = returnFunc(ctx, userID, currentUserID, take, lastID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.TrackWithLikedModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, int, int64) error); ok {
		r1 = returnFunc(ctx, userID, currentUserID, take, lastID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_GetManyPopular_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManyPopular'
type MockRepo_GetManyPopular_Call struct {
	*mock.Call
}

// GetManyPopular is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - currentUserID int64
//   - take int
//   - lastID int64
func (_e *MockRepo_Expecter) GetManyPopular(ctx interface{}, userID interface{}, currentUserID interface{}, take interface{}, lastID interface{}) *MockRepo_GetManyPopular_Call {
	return &MockRepo_GetManyPopular_Call{Call: _e.mock.On("GetManyPopular", ctx, userID, currentUserID, take, lastID)}
}

func (_c *MockRepo_GetManyPopular_Call) Run(run func(ctx context.Context, userID int64, currentUserID int64, take int, lastID int64)) *MockRepo_GetManyPopular_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepo_GetManyPopular_Call) Return(trackWithLikedModels []*models.TrackWithLikedModel, err error) *MockRepo_GetManyPopular_Call {
	_c.Call.Return(trackWithLikedModels, err)
	return _c
}

func (_c *MockRepo_GetManyPopular_Call) RunAndReturn(run func(ctx context.Context, userID int64, currentUserID int64, take int, lastID int64) ([]*models.TrackWithLikedModel, error)) *MockRepo_GetManyPopular_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFromLiked provides a mock function for the type MockRepo
func (_mock *MockRepo) RemoveFromLiked(ctx context.Context, currentUserID int64, trackID int64) error {
	ret := _mock.Called(ctx, currentUserID, trackID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFromLiked")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, currentUserID, trackID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepo_RemoveFromLiked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFromLiked'
type MockRepo_RemoveFromLiked_Call struct {
	*mock.Call
}

// RemoveFromLiked is a helper method to define mock.On call
//   - ctx context.Context
//   - currentUserID int64
//   - trackID int64
func (_e *MockRepo_Expecter) RemoveFromLiked(ctx interface{}, currentUserID interface{}, trackID interface{}) *MockRepo_RemoveFromLiked_Call {
	return &MockRepo_RemoveFromLiked_Call{Call: _e.mock.On("RemoveFromLiked", ctx, currentUserID, trackID)}
}

func (_c *MockRepo_RemoveFromLiked_Call) Run(run func(ctx context.Context, currentUserID int64, trackID int64)) *MockRepo_RemoveFromLiked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepo_RemoveFromLiked_Call) Return(err error) *MockRepo_RemoveFromLiked_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepo_RemoveFromLiked_Call) RunAndReturn(run func(ctx context.Context, currentUserID int64, trackID int64) error) *MockRepo_RemoveFromLiked_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileService creates a new instance of MockFileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileService {
	mock := &MockFileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileService is an autogenerated mock type for the FileService type
type MockFileService struct {
	mock.Mock
}

type MockFileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileService) EXPECT() *MockFileService_Expecter {
	return &MockFileService_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function for the type MockFileService
func (_mock *MockFileService) DeleteFile(ctx context.Context, fileName string, category file.Category) error {
	ret := _mock.Called(ctx, fileName, category)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, file.Category) error); ok {
		r0 = returnFunc(ctx, fileName, category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileService_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockFileService_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - fileName string
//   - category file.Category
func (_e *MockFileService_Expecter) DeleteFile(ctx interface{}, fileName interface{}, category interface{}) *MockFileService_DeleteFile_Call {
	return &MockFileService_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, fileName, category)}
}

func (_c *MockFileService_DeleteFile_Call) Run(run func(ctx context.Context, fileName string, category file.Category)) *MockFileService_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 file.Category
		if args[2] != nil {
			arg2 = args[2].(file.Category)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileService_DeleteFile_Call) Return(err error) *MockFileService_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileService_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, fileName string, category file.Category) error) *MockFileService_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAudio provides a mock function for the type MockFileService
func (_mock *MockFileService) SaveAudio(ctx context.Context, file1 *multipart.FileHeader) (*file.AudioResult, error) {
	ret := _mock.Called(ctx, file1)

	if len(ret) == 0 {
		panic("no return value specified for SaveAudio")
	}

	var r0 *file.AudioResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) (*file.AudioResult, error)); ok {
		return returnFunc(ctx, file1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) *file.AudioResult); ok {
		r0 = returnFunc(ctx, file1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file.AudioResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *multipart.FileHeader) error); ok {
		r1 = returnFunc(ctx, file1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileService_SaveAudio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAudio'
type MockFileService_SaveAudio_Call struct {
	*mock.Call
}

// SaveAudio is a helper method to define mock.On call
//   - ctx context.Context
//   - file1 *multipart.FileHeader
func (_e *MockFileService_Expecter) SaveAudio(ctx interface{}, file1 interface{}) *MockFileService_SaveAudio_Call {
	return &MockFileService_SaveAudio_Call{Call: _e.mock.On("SaveAudio", ctx, file1)}
}

func (_c *MockFileService_SaveAudio_Call) Run(run func(ctx context.Context, file1 *multipart.FileHeader)) *MockFileService_SaveAudio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *multipart.FileHeader
		if args[1] != nil {
			arg1 = args[1].(*multipart.FileHeader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileService_SaveAudio_Call) Return(audioResult *file.AudioResult, err error) *MockFileService_SaveAudio_Call {
	_c.Call.Return(audioResult, err)
	return _c
}

func (_c *MockFileService_SaveAudio_Call) RunAndReturn(run func(ctx context.Context, file1 *multipart.FileHeader) (*file.AudioResult, error)) *MockFileService_SaveAudio_Call {
	_c.Call.Return(run)
	return _c
}

// SaveImage provides a mock function for the type MockFileService
func (_mock *MockFileService) SaveImage(ctx context.Context, file1 *multipart.FileHeader) (string, error) {
	ret := _mock.Called(ctx, file1)

	if len(ret) == 0 {
		panic("no return value specified for SaveImage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) (string, error)); ok {
		return returnFunc(ctx, file1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) string); ok {
		r0 = returnFunc(ctx, file1)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *multipart.FileHeader) error); ok {
		r1 = returnFunc(ctx, file1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileService_SaveImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveImage'
type MockFileService_SaveImage_Call struct {
	*mock.Call
}

// SaveImage is a helper method to define mock.On call
//   - ctx context.Context
//   - file1 *multipart.FileHeader
func (_e *MockFileService_Expecter) SaveImage(ctx interface{}, file1 interface{}) *MockFileService_SaveImage_Call {
	return &MockFileService_SaveImage_Call{Call: _e.mock.On("SaveImage", ctx, file1)}
}

func (_c *MockFileService_SaveImage_Call) Run(run func(ctx context.Context, file1 *multipart.FileHeader)) *MockFileService_SaveImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *multipart.FileHeader
		if args[1] != nil {
			arg1 = args[1].(*multipart.FileHeader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileService_SaveImage_Call) Return(s string, err error) *MockFileService_SaveImage_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileService_SaveImage_Call) RunAndReturn(run func(ctx context.Context, file1 *multipart.FileHeader) (string, error)) *MockFileService_SaveImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSearchClient creates a new instance of MockSearchClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchClient {
	mock := &MockSearchClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSearchClient is an autogenerated mock type for the SearchClient type
type MockSearchClient struct {
	mock.Mock
}

type MockSearchClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchClient) EXPECT() *MockSearchClient_Expecter {
	return &MockSearchClient_Expecter{mock: &_m.Mock}
}

// AddTrack provides a mock function for the type MockSearchClient
func (_mock *MockSearchClient) AddTrack(ctx context.Context, req *searchservice.AddOrUpdateRequest) (*searchservice.SuccessResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AddTrack")
	}

	var r0 *searchservice.SuccessResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *searchservice.AddOrUpdateRequest) (*searchservice.SuccessResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *searchservice.AddOrUpdateRequest) *searchservice.SuccessResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*searchservice.SuccessResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *searchservice.AddOrUpdateRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSearchClient_AddTrack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTrack'
type MockSearchClient_AddTrack_Call struct {
	*mock.Call
}

// AddTrack is a helper method to define mock.On call
//   - ctx context.Context
//   - req *searchservice.AddOrUpdateRequest
func (_e *MockSearchClient_Expecter) AddTrack(ctx interface{}, req interface{}) *MockSearchClient_AddTrack_Call {
	return &MockSearchClient_AddTrack_Call{Call: _e.mock.On("AddTrack", ctx, req)}
}

func (_c *MockSearchClient_AddTrack_Call) Run(run func(ctx context.Context, req *searchservice.AddOrUpdateRequest)) *MockSearchClient_AddTrack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *searchservice.AddOrUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*searchservice.AddOrUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSearchClient_AddTrack_Call) Return(successResponse *searchservice.SuccessResponse, err error) *MockSearchClient_AddTrack_Call {
	_c.Call.Return(successResponse, err)
	return _c
}

func (_c *MockSearchClient_AddTrack_Call) RunAndReturn(run func(ctx context.Context, req *searchservice.AddOrUpdateRequest) (*searchservice.SuccessResponse, error)) *MockSearchClient_AddTrack_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTrack provides a mock function for the type MockSearchClient
func (_mock *MockSearchClient) DeleteTrack(ctx context.Context, req *searchservice.DeleteRequest) (*searchservice.SuccessResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTrack")
	}

	var r0 *searchservice.SuccessResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *searchservice.DeleteRequest) (*searchservice.SuccessResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *searchservice.DeleteRequest) *searchservice.SuccessResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*searchservice.SuccessResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *searchservice.DeleteRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSearchClient_DeleteTrack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTrack'
type MockSearchClient_DeleteTrack_Call struct {
	*mock.Call
}

// DeleteTrack is a helper method to define mock.On call
//   - ctx context.Context
//   - req *searchservice.DeleteRequest
func (_e *MockSearchClient_Expecter) DeleteTrack(ctx interface{}, req interface{}) *MockSearchClient_DeleteTrack_Call {
	return &MockSearchClient_DeleteTrack_Call{Call: _e.mock.On("DeleteTrack", ctx, req)}
}

func (_c *MockSearchClient_DeleteTrack_Call) Run(run func(ctx context.Context, req *searchservice.DeleteRequest)) *MockSearchClient_DeleteTrack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *searchservice.DeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*searchservice.DeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSearchClient_DeleteTrack_Call) Return(successResponse *searchservice.SuccessResponse, err error) *MockSearchClient_DeleteTrack_Call {
	_c.Call.Return(successResponse, err)
	return _c
}

func (_c *MockSearchClient_DeleteTrack_Call) RunAndReturn(run func(ctx context.Context, req *searchservice.DeleteRequest) (*searchservice.SuccessResponse, error)) *MockSearchClient_DeleteTrack_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTrack provides a mock function for the type MockSearchClient
func (_mock *MockSearchClient) UpdateTrack(ctx context.Context, req *searchservice.AddOrUpdateRequest) (*searchservice.SuccessResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTrack")
	}

	var r0 *searchservice.SuccessResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *searchservice.AddOrUpdateRequest) (*searchservice.SuccessResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *searchservice.AddOrUpdateRequest) *searchservice.SuccessResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*searchservice.SuccessResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *searchservice.AddOrUpdateRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSearchClient_UpdateTrack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTrack'
type MockSearchClient_UpdateTrack_Call struct {
	*mock.Call
}

// UpdateTrack is a helper method to define mock.On call
//   - ctx context.Context
//   - req *searchservice.AddOrUpdateRequest
func (_e *MockSearchClient_Expecter) UpdateTrack(ctx interface{}, req interface{}) *MockSearchClient_UpdateTrack_Call {
	return &MockSearchClient_UpdateTrack_Call{Call: _e.mock.On("UpdateTrack", ctx, req)}
}

func (_c *MockSearchClient_UpdateTrack_Call) Run(run func(ctx context.Context, req *searchservice.AddOrUpdateRequest)) *MockSearchClient_UpdateTrack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *searchservice.AddOrUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*searchservice.AddOrUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSearchClient_UpdateTrack_Call) Return(successResponse *searchservice.SuccessResponse, err error) *MockSearchClient_UpdateTrack_Call {
	_c.Call.Return(successResponse, err)
	return _c
}

func (_c *MockSearchClient_UpdateTrack_Call) RunAndReturn(run func(ctx context.Context, req *searchservice.AddOrUpdateRequest) (*searchservice.SuccessResponse, error)) *MockSearchClient_UpdateTrack_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationClient creates a new instance of MockNotificationClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationClient {
	mock := &MockNotificationClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationClient is an autogenerated mock type for the NotificationClient type
type MockNotificationClient struct {
	mock.Mock
}

type MockNotificationClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationClient) EXPECT() *MockNotificationClient_Expecter {
	return &MockNotificationClient_Expecter{mock: &_m.Mock}
}

// SendEmailNotification provides a mock function for the type MockNotificationClient
func (_mock *MockNotificationClient) SendEmailNotification(ctx context.Context, email string, msg string) error {
	ret := _mock.Called(ctx, email, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendEmailNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, email, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationClient_SendEmailNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmailNotification'
type MockNotificationClient_SendEmailNotification_Call struct {
	*mock.Call
}

// SendEmailNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - msg string
func (_e *MockNotificationClient_Expecter) SendEmailNotification(ctx interface{}, email interface{}, msg interface{}) *MockNotificationClient_SendEmailNotification_Call {
	return &MockNotificationClient_SendEmailNotification_Call{Call: _e.mock.On("SendEmailNotification", ctx, email, msg)}
}

func (_c *MockNotificationClient_SendEmailNotification_Call) Run(run func(ctx context.Context, email string, msg string)) *MockNotificationClient_SendEmailNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationClient_SendEmailNotification_Call) Return(err error) *MockNotificationClient_SendEmailNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationClient_SendEmailNotification_Call) RunAndReturn(run func(ctx context.Context, email string, msg string) error) *MockNotificationClient_SendEmailNotification_Call {
	_c.Call.Return(run)
	return _c
}
