apiVersion: v1
kind: Secret
metadata:
  name: content-service-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
  CLOUDINARY_CLOUD_NAME: cloudinary_cloud_name
  CLOUDINARY_API_KEY: cloudinary_api_key
  CLOUDINARY_API_SECRET: cloudinary_api_secret
