apiVersion: v1
kind: Service
metadata:
  name: content-service-app
  labels:
    app: content-service
spec:
  selector:
    app: content-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
