// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"github.com/golang-jwt/jwt/v5"
	"github.com/ocenb/music-go/user-service/internal/models"
	"github.com/ocenb/music-protos/gen/userservice"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// ChangeEmail provides a mock function for the type MockUserService
func (_mock *MockUserService) ChangeEmail(ctx context.Context, userID int64, email string) (*userservice.UserPrivateModel, error) {
	ret := _mock.Called(ctx, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for ChangeEmail")
	}

	var r0 *userservice.UserPrivateModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (*userservice.UserPrivateModel, error)); ok {
		return returnFunc(ctx, userID, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) *userservice.UserPrivateModel); ok {
		r0 = returnFunc(ctx, userID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userservice.UserPrivateModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_ChangeEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeEmail'
type MockUserService_ChangeEmail_Call struct {
	*mock.Call
}

// ChangeEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - email string
func (_e *MockUserService_Expecter) ChangeEmail(ctx interface{}, userID interface{}, email interface{}) *MockUserService_ChangeEmail_Call {
	return &MockUserService_ChangeEmail_Call{Call: _e.mock.On("ChangeEmail", ctx, userID, email)}
}

func (_c *MockUserService_ChangeEmail_Call) Run(run func(ctx context.Context, userID int64, email string)) *MockUserService_ChangeEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_ChangeEmail_Call) Return(userPrivateModel *userservice.UserPrivateModel, err error) *MockUserService_ChangeEmail_Call {
	_c.Call.Return(userPrivateModel, err)
	return _c
}

func (_c *MockUserService_ChangeEmail_Call) RunAndReturn(run func(ctx context.Context, userID int64, email string) (*userservice.UserPrivateModel, error)) *MockUserService_ChangeEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ChangePassword provides a mock function for the type MockUserService
func (_mock *MockUserService) ChangePassword(ctx context.Context, userID int64, password string) (*userservice.UserPrivateModel, error) {
	ret := _mock.Called(ctx, userID, password)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 *userservice.UserPrivateModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (*userservice.UserPrivateModel, error)); ok {
		return returnFunc(ctx, userID, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) *userservice.UserPrivateModel); ok {
		r0 = returnFunc(ctx, userID, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userservice.UserPrivateModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockUserService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - password string
func (_e *MockUserService_Expecter) ChangePassword(ctx interface{}, userID interface{}, password interface{}) *MockUserService_ChangePassword_Call {
	return &MockUserService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, password)}
}

func (_c *MockUserService_ChangePassword_Call) Run(run func(ctx context.Context, userID int64, password string)) *MockUserService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_ChangePassword_Call) Return(userPrivateModel *userservice.UserPrivateModel, err error) *MockUserService_ChangePassword_Call {
	_c.Call.Return(userPrivateModel, err)
	return _c
}

func (_c *MockUserService_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, userID int64, password string) (*userservice.UserPrivateModel, error)) *MockUserService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockUserService
func (_mock *MockUserService) Create(ctx context.Context, username string, email string, password string, verificationToken string) (*userservice.UserPrivateModel, error) {
	ret := _mock.Called(ctx, username, email, password, verificationToken)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *userservice.UserPrivateModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*userservice.UserPrivateModel, error)); ok {
		return returnFunc(ctx, username, email, password, verificationToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *userservice.UserPrivateModel); ok {
		r0 = returnFunc(ctx, username, email, password, verificationToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userservice.UserPrivateModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, username, email, password, verificationToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - email string
//   - password string
//   - verificationToken string
func (_e *MockUserService_Expecter) Create(ctx interface{}, username interface{}, email interface{}, password interface{}, verificationToken interface{}) *MockUserService_Create_Call {
	return &MockUserService_Create_Call{Call: _e.mock.On("Create", ctx, username, email, password, verificationToken)}
}

func (_c *MockUserService_Create_Call) Run(run func(ctx context.Context, username string, email string, password string, verificationToken string)) *MockUserService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUserService_Create_Call) Return(userPrivateModel *userservice.UserPrivateModel, err error) *MockUserService_Create_Call {
	_c.Call.Return(userPrivateModel, err)
	return _c
}

func (_c *MockUserService_Create_Call) RunAndReturn(run func(ctx context.Context, username string, email string, password string, verificationToken string) (*userservice.UserPrivateModel, error)) *MockUserService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockUserService
func (_mock *MockUserService) GetByEmail(ctx context.Context, email string) (*models.UserFullModel, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.UserFullModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.UserFullModel, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.UserFullModel); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserFullModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserService_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserService_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockUserService_GetByEmail_Call {
	return &MockUserService_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserService_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserService_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetByEmail_Call) Return(userFullModel *models.UserFullModel, err error) *MockUserService_GetByEmail_Call {
	_c.Call.Return(userFullModel, err)
	return _c
}

func (_c *MockUserService_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.UserFullModel, error)) *MockUserService_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockUserService
func (_mock *MockUserService) GetByID(ctx context.Context, id int64) (*models.UserFullModel, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.UserFullModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*models.UserFullModel, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *models.UserFullModel); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserFullModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUserService_Expecter) GetByID(ctx interface{}, id interface{}) *MockUserService_GetByID_Call {
	return &MockUserService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserService_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockUserService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetByID_Call) Return(userFullModel *models.UserFullModel, err error) *MockUserService_GetByID_Call {
	_c.Call.Return(userFullModel, err)
	return _c
}

func (_c *MockUserService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*models.UserFullModel, error)) *MockUserService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function for the type MockUserService
func (_mock *MockUserService) GetByUsername(ctx context.Context, username string) (*userservice.UserPublicModel, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *userservice.UserPublicModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*userservice.UserPublicModel, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *userservice.UserPublicModel); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userservice.UserPublicModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockUserService_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserService_Expecter) GetByUsername(ctx interface{}, username interface{}) *MockUserService_GetByUsername_Call {
	return &MockUserService_GetByUsername_Call{Call: _e.mock.On("GetByUsername", ctx, username)}
}

func (_c *MockUserService_GetByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserService_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetByUsername_Call) Return(userPublicModel *userservice.UserPublicModel, err error) *MockUserService_GetByUsername_Call {
	_c.Call.Return(userPublicModel, err)
	return _c
}

func (_c *MockUserService_GetByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*userservice.UserPublicModel, error)) *MockUserService_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetByVerificationToken provides a mock function for the type MockUserService
func (_mock *MockUserService) GetByVerificationToken(ctx context.Context, verificationToken string) (*models.UserFullModel, error) {
	ret := _mock.Called(ctx, verificationToken)

	if len(ret) == 0 {
		panic("no return value specified for GetByVerificationToken")
	}

	var r0 *models.UserFullModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.UserFullModel, error)); ok {
		return returnFunc(ctx, verificationToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.UserFullModel); ok {
		r0 = returnFunc(ctx, verificationToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserFullModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, verificationToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetByVerificationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByVerificationToken'
type MockUserService_GetByVerificationToken_Call struct {
	*mock.Call
}

// GetByVerificationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - verificationToken string
func (_e *MockUserService_Expecter) GetByVerificationToken(ctx interface{}, verificationToken interface{}) *MockUserService_GetByVerificationToken_Call {
	return &MockUserService_GetByVerificationToken_Call{Call: _e.mock.On("GetByVerificationToken", ctx, verificationToken)}
}

func (_c *MockUserService_GetByVerificationToken_Call) Run(run func(ctx context.Context, verificationToken string)) *MockUserService_GetByVerificationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetByVerificationToken_Call) Return(userFullModel *models.UserFullModel, err error) *MockUserService_GetByVerificationToken_Call {
	_c.Call.Return(userFullModel, err)
	return _c
}

func (_c *MockUserService_GetByVerificationToken_Call) RunAndReturn(run func(ctx context.Context, verificationToken string) (*models.UserFullModel, error)) *MockUserService_GetByVerificationToken_Call {
	_c.Call.Return(run)
	return _c
}

// SetVerified provides a mock function for the type MockUserService
func (_mock *MockUserService) SetVerified(ctx context.Context, userID int64) (*userservice.UserPrivateModel, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SetVerified")
	}

	var r0 *userservice.UserPrivateModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*userservice.UserPrivateModel, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *userservice.UserPrivateModel); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userservice.UserPrivateModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_SetVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVerified'
type MockUserService_SetVerified_Call struct {
	*mock.Call
}

// SetVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockUserService_Expecter) SetVerified(ctx interface{}, userID interface{}) *MockUserService_SetVerified_Call {
	return &MockUserService_SetVerified_Call{Call: _e.mock.On("SetVerified", ctx, userID)}
}

func (_c *MockUserService_SetVerified_Call) Run(run func(ctx context.Context, userID int64)) *MockUserService_SetVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_SetVerified_Call) Return(userPrivateModel *userservice.UserPrivateModel, err error) *MockUserService_SetVerified_Call {
	_c.Call.Return(userPrivateModel, err)
	return _c
}

func (_c *MockUserService_SetVerified_Call) RunAndReturn(run func(ctx context.Context, userID int64) (*userservice.UserPrivateModel, error)) *MockUserService_SetVerified_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVerificationToken provides a mock function for the type MockUserService
func (_mock *MockUserService) UpdateVerificationToken(ctx context.Context, userID int64, newVerificationToken string) (*userservice.UserPrivateModel, error) {
	ret := _mock.Called(ctx, userID, newVerificationToken)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVerificationToken")
	}

	var r0 *userservice.UserPrivateModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (*userservice.UserPrivateModel, error)); ok {
		return returnFunc(ctx, userID, newVerificationToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) *userservice.UserPrivateModel); ok {
		r0 = returnFunc(ctx, userID, newVerificationToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userservice.UserPrivateModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, newVerificationToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_UpdateVerificationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVerificationToken'
type MockUserService_UpdateVerificationToken_Call struct {
	*mock.Call
}

// UpdateVerificationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - newVerificationToken string
func (_e *MockUserService_Expecter) UpdateVerificationToken(ctx interface{}, userID interface{}, newVerificationToken interface{}) *MockUserService_UpdateVerificationToken_Call {
	return &MockUserService_UpdateVerificationToken_Call{Call: _e.mock.On("UpdateVerificationToken", ctx, userID, newVerificationToken)}
}

func (_c *MockUserService_UpdateVerificationToken_Call) Run(run func(ctx context.Context, userID int64, newVerificationToken string)) *MockUserService_UpdateVerificationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_UpdateVerificationToken_Call) Return(userPrivateModel *userservice.UserPrivateModel, err error) *MockUserService_UpdateVerificationToken_Call {
	_c.Call.Return(userPrivateModel, err)
	return _c
}

func (_c *MockUserService_UpdateVerificationToken_Call) RunAndReturn(run func(ctx context.Context, userID int64, newVerificationToken string) (*userservice.UserPrivateModel, error)) *MockUserService_UpdateVerificationToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// CreateTokens provides a mock function for the type MockTokenService
func (_mock *MockTokenService) CreateTokens(ctx context.Context, userID int64) (string, string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateTokens")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (string, string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) string); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenService_CreateTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTokens'
type MockTokenService_CreateTokens_Call struct {
	*mock.Call
}

// CreateTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockTokenService_Expecter) CreateTokens(ctx interface{}, userID interface{}) *MockTokenService_CreateTokens_Call {
	return &MockTokenService_CreateTokens_Call{Call: _e.mock.On("CreateTokens", ctx, userID)}
}

func (_c *MockTokenService_CreateTokens_Call) Run(run func(ctx context.Context, userID int64)) *MockTokenService_CreateTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_CreateTokens_Call) Return(s string, s1 string, err error) *MockTokenService_CreateTokens_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockTokenService_CreateTokens_Call) RunAndReturn(run func(ctx context.Context, userID int64) (string, string, error)) *MockTokenService_CreateTokens_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateVerificationToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GenerateVerificationToken() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateVerificationToken")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTokenService_GenerateVerificationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateVerificationToken'
type MockTokenService_GenerateVerificationToken_Call struct {
	*mock.Call
}

// GenerateVerificationToken is a helper method to define mock.On call
func (_e *MockTokenService_Expecter) GenerateVerificationToken() *MockTokenService_GenerateVerificationToken_Call {
	return &MockTokenService_GenerateVerificationToken_Call{Call: _e.mock.On("GenerateVerificationToken")}
}

func (_c *MockTokenService_GenerateVerificationToken_Call) Run(run func()) *MockTokenService_GenerateVerificationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenService_GenerateVerificationToken_Call) Return(s string) *MockTokenService_GenerateVerificationToken_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTokenService_GenerateVerificationToken_Call) RunAndReturn(run func() string) *MockTokenService_GenerateVerificationToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenByID provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GetTokenByID(ctx context.Context, tokenID string) (*models.TokenModel, error) {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenByID")
	}

	var r0 *models.TokenModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.TokenModel, error)); ok {
		return returnFunc(ctx, tokenID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.TokenModel); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TokenModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_GetTokenByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenByID'
type MockTokenService_GetTokenByID_Call struct {
	*mock.Call
}

// GetTokenByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockTokenService_Expecter) GetTokenByID(ctx interface{}, tokenID interface{}) *MockTokenService_GetTokenByID_Call {
	return &MockTokenService_GetTokenByID_Call{Call: _e.mock.On("GetTokenByID", ctx, tokenID)}
}

func (_c *MockTokenService_GetTokenByID_Call) Run(run func(ctx context.Context, tokenID string)) *MockTokenService_GetTokenByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_GetTokenByID_Call) Return(tokenModel *models.TokenModel, err error) *MockTokenService_GetTokenByID_Call {
	_c.Call.Return(tokenModel, err)
	return _c
}

func (_c *MockTokenService_GetTokenByID_Call) RunAndReturn(run func(ctx context.Context, tokenID string) (*models.TokenModel, error)) *MockTokenService_GetTokenByID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllTokens provides a mock function for the type MockTokenService
func (_mock *MockTokenService) RevokeAllTokens(ctx context.Context, userID int64) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllTokens")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenService_RevokeAllTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllTokens'
type MockTokenService_RevokeAllTokens_Call struct {
	*mock.Call
}

// RevokeAllTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockTokenService_Expecter) RevokeAllTokens(ctx interface{}, userID interface{}) *MockTokenService_RevokeAllTokens_Call {
	return &MockTokenService_RevokeAllTokens_Call{Call: _e.mock.On("RevokeAllTokens", ctx, userID)}
}

func (_c *MockTokenService_RevokeAllTokens_Call) Run(run func(ctx context.Context, userID int64)) *MockTokenService_RevokeAllTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_RevokeAllTokens_Call) Return(err error) *MockTokenService_RevokeAllTokens_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenService_RevokeAllTokens_Call) RunAndReturn(run func(ctx context.Context, userID int64) error) *MockTokenService_RevokeAllTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) RevokeToken(ctx context.Context, tokenID string) error {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenService_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockTokenService_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockTokenService_Expecter) RevokeToken(ctx interface{}, tokenID interface{}) *MockTokenService_RevokeToken_Call {
	return &MockTokenService_RevokeToken_Call{Call: _e.mock.On("RevokeToken", ctx, tokenID)}
}

func (_c *MockTokenService_RevokeToken_Call) Run(run func(ctx context.Context, tokenID string)) *MockTokenService_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_RevokeToken_Call) Return(err error) *MockTokenService_RevokeToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenService_RevokeToken_Call) RunAndReturn(run func(ctx context.Context, tokenID string) error) *MockTokenService_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) ValidateToken(tokenString string) (jwt.MapClaims, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 jwt.MapClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (jwt.MapClaims, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) jwt.MapClaims); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.MapClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockTokenService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - tokenString string
func (_e *MockTokenService_Expecter) ValidateToken(tokenString interface{}) *MockTokenService_ValidateToken_Call {
	return &MockTokenService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", tokenString)}
}

func (_c *MockTokenService_ValidateToken_Call) Run(run func(tokenString string)) *MockTokenService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_ValidateToken_Call) Return(mapClaims jwt.MapClaims, err error) *MockTokenService_ValidateToken_Call {
	_c.Call.Return(mapClaims, err)
	return _c
}

func (_c *MockTokenService_ValidateToken_Call) RunAndReturn(run func(tokenString string) (jwt.MapClaims, error)) *MockTokenService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationClient creates a new instance of MockNotificationClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationClient {
	mock := &MockNotificationClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationClient is an autogenerated mock type for the NotificationClient type
type MockNotificationClient struct {
	mock.Mock
}

type MockNotificationClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationClient) EXPECT() *MockNotificationClient_Expecter {
	return &MockNotificationClient_Expecter{mock: &_m.Mock}
}

// SendEmailNotification provides a mock function for the type MockNotificationClient
func (_mock *MockNotificationClient) SendEmailNotification(ctx context.Context, email string, msg string) error {
	ret := _mock.Called(ctx, email, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendEmailNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, email, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationClient_SendEmailNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmailNotification'
type MockNotificationClient_SendEmailNotification_Call struct {
	*mock.Call
}

// SendEmailNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - msg string
func (_e *MockNotificationClient_Expecter) SendEmailNotification(ctx interface{}, email interface{}, msg interface{}) *MockNotificationClient_SendEmailNotification_Call {
	return &MockNotificationClient_SendEmailNotification_Call{Call: _e.mock.On("SendEmailNotification", ctx, email, msg)}
}

func (_c *MockNotificationClient_SendEmailNotification_Call) Run(run func(ctx context.Context, email string, msg string)) *MockNotificationClient_SendEmailNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotificationClient_SendEmailNotification_Call) Return(err error) *MockNotificationClient_SendEmailNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationClient_SendEmailNotification_Call) RunAndReturn(run func(ctx context.Context, email string, msg string) error) *MockNotificationClient_SendEmailNotification_Call {
	_c.Call.Return(run)
	return _c
}
