services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: search-service-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - music-go-network

  app:
    build: .
    container_name: search-service-app
    env_file:
      - .env
    ports:
      - "9091:9091"
    volumes:
      - ./.env:/app/.env
      - ./config:/app/config
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: always
    networks:
      - music-go-network

volumes:
  elasticsearch_data:
    driver: local

networks:
  music-go-network:
    name: music-go-network
    external: true
