apiVersion: v1
kind: ConfigMap
metadata:
  name: search-service-config
data:
  local.yaml: |
    grpc:
      port: 9091
      timeout: 5s
    log_level: 0
    log_handler: text
    shutdown_timeout: 10s
    elastic_connect_timeout: 10s
