apiVersion: v1
kind: Service
metadata:
  name: search-service-app
  labels:
    app: search-service
spec:
  selector:
    app: search-service
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  type: ClusterIP
